# Generated by Django 4.1.4 on 2022-12-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnoses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domains',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
