# Generated by Django 2.2.13 on 2022-12-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnoses', '0002_classes_slug_domains_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnoses',
            old_name='description',
            new_name='definition',
        ),
        migrations.RenameField(
            model_name='diagnoses',
            old_name='title',
            new_name='diagnosis',
        ),
        migrations.AddField(
            model_name='diagnoses',
            name='associated_condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnoses',
            name='at_risk_population',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnoses',
            name='defining_characteristics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnoses',
            name='nic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnoses',
            name='noc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='diagnoses',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='domains',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
