# Generated by Django 2.2.13 on 2022-12-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnoses', '0003_auto_20221213_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnoses',
            name='diagnosis_code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
