# Generated by Django 2.2.13 on 2022-12-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnoses', '0004_diagnoses_diagnosis_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnoses',
            name='related_factors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
