# Generated by Django 2.2.13 on 2022-12-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnoses', '0005_diagnoses_related_factors'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnoses',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
