# Generated by Django 4.1.4 on 2022-12-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnoses', '0008_alter_diagnoses_accepted_alter_diagnoses_classe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='diagnoses',
            name='diagnosis',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='diagnoses',
            name='diagnosis_code',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='diagnoses',
            name='slug',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='domains',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='domains',
            name='number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='domains',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
