# Generated by Django 4.1.4 on 2022-12-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnoses', '0009_alter_classes_name_alter_classes_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='domains',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
