# Generated by Django 4.1.4 on 2022-12-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnoses', '0010_alter_classes_number_alter_domains_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='classes',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnoses',
            name='diagnosis',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='diagnoses',
            name='diagnosis_code',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='diagnoses',
            name='slug',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='domains',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='domains',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
